# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a100tcsg324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir {H:/My Documents/CSE260M/lab1/lab1.cache/wt} [current_project]
set_property parent.project_path {H:/My Documents/CSE260M/lab1/lab1.xpr} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
read_vhdl -library xil_defaultlib {{H:/My Documents/CSE260M/lab1/lab1.srcs/sources_1/new/lab1.vhd}}
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc {{H:/My Documents/CSE260M/lab1/lab1.srcs/constrs_1/new/lab1constraints.xdc}}
set_property used_in_implementation false [get_files {{H:/My Documents/CSE260M/lab1/lab1.srcs/constrs_1/new/lab1constraints.xdc}}]


synth_design -top params -part xc7a100tcsg324-1


write_checkpoint -force -noxdef params.dcp

catch { report_utilization -file params_utilization_synth.rpt -pb params_utilization_synth.pb }
