
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Mon Apr 17 15:35:16 CDT 2017
//----------------------------------------------------

package exam1.autogen;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int tag = 6;
  public static final int error = 1;
  public static final int link = 7;
  public static final int text = 5;
  public static final int ltag_o = 2;
  public static final int EOF = 0;
  public static final int ltag_c = 4;
  public static final int rtag = 3;
}

